

import { Card, CardRarity } from '../types';

// This file contains the complete, pre-generated card database for all 2,668 cards.
// This allows for an instant, offline-first application startup without relying on AI generation at runtime.
// This is the definitive, high-quality version of the database.

const placeholderFront = 'https://images.unsplash.com/photo-1534796636912-3b95b3ab5986?q=80&w=1974';
const newCardBackUrl = "https://i.imgur.com/z11n4j7.jpeg";

const generateAllCards = (): Card[] => {
    const allCards: Card[] = [
        // --- SEASON 1: Genesis Era ---
        // Common
        {
            "id": "1-Common-1",
            "name": { "th": "ก็อบลินสอดแนม", "en": "Goblin Scout" },
            "rarity": "Common",
            "season": 1,
            "cardNumber": 1,
            "element": "Earth",
            "tribe": "Orc",
            "description": { "th": "หน่วยสอดแนมผู้ปราดเปรียว ว่องไวและเจ้าเล่ห์ คอยหาช่องโหว่ของศัตรู", "en": "A swift and cunning scout, always looking for enemy weaknesses." },
            "story": { "th": "ก็อบลินสอดแนมเป็นแนวหน้าของทุกกองทัพก็อบลิน พวกมันอาจไม่แข็งแกร่ง แต่ความเร็วและความสามารถในการลอบเร้นทำให้พวกมันเป็นผู้รวบรวมข้อมูลที่ประเมินค่าไม่ได้ พวกมันสามารถแทรกซึมเข้าไปในค่ายของศัตรูและกลับออกมาพร้อมกับแผนผังและจำนวนกำลังพลโดยไม่มีใครสังเกตเห็น", "en": "Goblin Scouts are the vanguard of any goblin army. They may not be strong, but their speed and stealth make them invaluable information gatherers. They can infiltrate enemy camps and return with layouts and troop numbers unnoticed." },
            "stats": { "attack": 12, "defense": 8, "speed": 20, "hp": 25 },
            "frontImage": placeholderFront,
            "backImage": newCardBackUrl
        },
        {
            "id": "1-Common-2",
            "name": { "th": "ภูตพฤกษา", "en": "Forest Sprite" },
            "rarity": "Common",
            "season": 1,
            "cardNumber": 2,
            "element": "Wind",
            "tribe": "Fairy",
            "description": { "th": "วิญญาณแห่งป่าผู้ขี้อาย คอยปกป้องเหล่าพืชและสัตว์จากอันตราย", "en": "A shy spirit of the forest that protects flora and fauna from harm." },
            "story": { "th": "ภูตพฤกษาถือกำเนิดจากน้ำค้างบนใบไม้แรกของฤดูใบไม้ผลิ พวกมันสื่อสารกับต้นไม้และนำทางสัตว์ที่หลงทางให้กลับบ้าน แม้จะดูบอบบาง แต่เมื่อป่าถูกคุกคาม พวกมันจะรวมตัวกันสร้างพายุใบไม้ที่คมกริบเพื่อขับไล่ผู้บุกรุก", "en": "Born from the dew on the first leaf of spring, Forest Sprites communicate with trees and guide lost animals home. Though they appear delicate, when the forest is threatened, they gather to create storms of razor-sharp leaves to repel intruders." },
            "stats": { "attack": 8, "defense": 12, "speed": 18, "hp": 30 },
            "frontImage": placeholderFront,
            "backImage": newCardBackUrl
        },
        {
            "id": "1-Common-3",
            "name": { "th": "นักรบโครงกระดูก", "en": "Skeleton Warrior" },
            "rarity": "Common",
            "season": 1,
            "cardNumber": 3,
            "element": "Dark",
            "tribe": "Undead",
            "description": { "th": "ทหารที่ถูกปลุกชีพด้วยมนต์ดำ ต่อสู้อย่างไม่รู้จักเหนื่อย", "en": "A soldier reanimated by dark sorcery, fighting tirelessly." },
            "story": { "th": "ครั้งหนึ่งเคยเป็นทหารผู้ภักดีในสนามรบ บัดนี้เหลือเพียงกองกระดูกที่เคลื่อนไหวตามคำสั่งของจอมขมังเวทย์ผู้ปลุกชีพมันขึ้นมา มันไม่รู้สึกเจ็บปวดหรือความกลัว และจะต่อสู้ต่อไปจนกว่าร่างกายจะแหลกสลายเป็นผุยผงหรือมนต์ดำที่ควบคุมมันจะสลายไป", "en": "Once a loyal soldier on the battlefield, now a pile of bones animated by the will of its necromantic master. It feels no pain or fear and will continue to fight until its body is dust or the dark magic binding it is broken." },
            "stats": { "attack": 15, "defense": 10, "speed": 10, "hp": 28 },
            "frontImage": placeholderFront,
            "backImage": newCardBackUrl
        },
        {
            "id": "1-Common-4",
            "name": { "th": "สไลม์แห่งถ้ำ", "en": "Cavern Slime" },
            "rarity": "Common",
            "season": 1,
            "cardNumber": 4,
            "element": "Water",
            "tribe": "Elemental",
            "description": { "th": "สิ่งมีชีวิตเรียบง่ายที่ย่อยสลายแร่ธาตุเพื่อเติบโต", "en": "A simple creature that dissolves minerals to grow." },
            "story": { "th": "สไลม์เหล่านี้พบได้ทั่วไปในถ้ำที่ชื้นแฉะ พวกมันไม่มีสติปัญญา แต่จะเคลื่อนที่เข้าหาแหล่งแร่ธาตุและอาหารอย่างช้าๆ ร่างกายที่เป็นกรดของมันสามารถย่อยสลายได้แม้กระทั่งหินที่แข็งที่สุด ซึ่งเป็นส่วนสำคัญของระบบนิเวศใต้ดิน แต่ก็เป็นอันตรายต่อนักผจญภัยที่ไม่ระวังตัว", "en": "Commonly found in damp caves, these slimes lack intelligence but slowly move towards mineral and food sources. Their acidic bodies can dissolve even the hardest stone, making them a key part of the subterranean ecosystem but a danger to unwary adventurers." },
            "stats": { "attack": 10, "defense": 15, "speed": 5, "hp": 35 },
            "frontImage": placeholderFront,
            "backImage": newCardBackUrl
        },
        {
            "id": "1-Common-5",
            "name": { "th": "หมาป่าภูเขา", "en": "Mountain Wolf" },
            "rarity": "Common",
            "season": 1,
            "cardNumber": 5,
            "element": "Earth",
            "tribe": "Beast",
            "description": { "th": "นักล่าที่ปรับตัวเข้ากับสภาพแวดล้อมบนภูเขาสูง", "en": "A predator adapted to high-altitude environments." },
            "story": { "th": "หมาป่าภูเขามีขนสีเทาหนาเพื่อป้องกันความหนาวเย็นและกล้ามเนื้อขาที่แข็งแรงเพื่อปีนป่ายไปตามโขดหิน พวกมันออกล่าเป็นฝูงโดยใช้กลยุทธ์ที่ซับซ้อนเพื่อล้อมเหยื่อ เสียงหอนของพวกมันที่ดังสะท้อนไปทั่วหุบเขาเป็นสัญญาณเตือนถึงอันตรายสำหรับนักเดินทางทุกคน", "en": "With thick grey fur to ward off the cold and powerful legs for navigating rocky terrain, Mountain Wolves hunt in packs using complex strategies to corner their prey. Their howls echoing through the valleys are a warning sign to all travelers." },
            "stats": { "attack": 18, "defense": 9, "speed": 17, "hp": 26 },
            "frontImage": placeholderFront,
            "backImage": newCardBackUrl
        },
        {
            "id": "1-Common-6",
            "name": { "th": "ทหารราบฝึกหัด", "en": "Rookie Soldier" },
            "rarity": "Common",
            "season": 1,
            "cardNumber": 6,
            "element": "Earth",
            "tribe": "Human",
            "description": { "th": "ทหารใหม่ผู้มีความฝันอันยิ่งใหญ่ แต่ยังขาดประสบการณ์", "en": "A new soldier with big dreams but little experience." },
            "story": { "th": "ทุกคนต้องมีจุดเริ่มต้น ทหารราบฝึกหัดคือกระดูกสันหลังของทุกอาณาจักร พวกเขาอาจจะยังเงอะงะในการใช้ดาบและหวาดกลัวเสียงคำรามของมังกร แต่ภายใต้ความกลัวนั้นคือความกล้าหาญที่รอวันเบ่งบาน การฝึกฝนทุกวันคือบทเรียน และทุกสมรภูมิคือโอกาสในการพิสูจน์ตัวเอง", "en": "Everyone has to start somewhere. Rookie Soldiers are the backbone of any kingdom. They might still be clumsy with their swords and terrified by a dragon's roar, but beneath that fear lies a bravery waiting to bloom. Every training day is a lesson, and every battlefield is a chance to prove themselves." },
            "stats": { "attack": 14, "defense": 12, "speed": 11, "hp": 32 },
            "frontImage": placeholderFront,
            "backImage": newCardBackUrl
        },
        {
            "id": "1-Common-7",
            "name": { "th": "อิฟริตน้อย", "en": "Lesser Ifrit" },
            "rarity": "Common",
            "season": 1,
            "cardNumber": 7,
            "element": "Fire",
            "tribe": "Elemental",
            "description": { "th": "ภูตไฟตัวเล็กที่เกิดจากเปลวเพลิง มีนิสัยขี้เล่นและอันตราย", "en": "A small fire elemental born of flame, playful yet dangerous." },
            "story": { "th": "อิฟริตน้อยชอบเต้นรำไปตามกองไฟและไล่จับประกายไฟเล่น พวกมันคือจิตวิญญาณแห่งเปลวเพลิงที่บริสุทธิ์ แม้การเล่นของพวกมันอาจดูไม่มีพิษมีภัย แต่มันสามารถเปลี่ยนเป็นไฟป่าที่โหมกระหน่ำได้ในพริบตาหากถูกยั่วยุ นักเวทย์บางคนพยายามจับพวกมันมาเป็นผู้รับใช้ แต่ส่วนใหญ่มักจบลงด้วยห้องทดลองที่ไหม้เป็นเถ้าถ่าน", "en": "Lesser Ifrits love to dance in campfires and chase sparks. They are pure spirits of flame. While their play may seem harmless, it can turn into a raging wildfire in an instant if they are provoked. Some mages try to capture them as servants, but it usually ends with a laboratory burnt to ashes." },
            "stats": { "attack": 19, "defense": 7, "speed": 16, "hp": 24 },
            "frontImage": placeholderFront,
            "backImage": newCardBackUrl
        },
        {
            "id": "1-Common-8",
            "name": { "th": "ค้างคาวดูดเลือด", "en": "Vampiric Bat" },
            "rarity": "Common",
            "season": 1,
            "cardNumber": 8,
            "element": "Dark",
            "tribe": "Beast",
            "description": { "th": "ค้างคาวที่อาศัยอยู่ในถ้ำมืดและดูดพลังชีวิตจากเหยื่อ", "en": "A bat that dwells in dark caves and drains life from its prey." },
            "story": { "th": "อย่าได้ดูถูกขนาดตัวที่เล็กของมัน ค้างคาวดูดเลือดเคลื่อนไหวในความมืดได้อย่างเงียบเชียบและรวดเร็ว การกัดของมันไม่เพียงแต่สร้างความเจ็บปวด แต่ยังดูดพลังชีวิตของเหยื่อมาฟื้นฟูตัวเอง พวกมันมักจะออกล่าเป็นฝูงใหญ่ในคืนเดือนมืด เปลี่ยนท้องฟ้ายามค่ำคืนให้กลายเป็นเงาแห่งความตาย", "en": "Do not underestimate its small size. The Vampiric Bat moves silently and swiftly in the darkness. Its bite not only causes pain but also drains the life force of its victim to heal itself. They often hunt in large swarms on moonless nights, turning the night sky into a shadow of death." },
            "stats": { "attack": 13, "defense": 6, "speed": 22, "hp": 20 },
            "frontImage": placeholderFront,
            "backImage": newCardBackUrl
        },
        {
            "id": "1-Common-9",
            "name": { "th": "นักธนูเอลฟ์ฝึกหัด", "en": "Elf Apprentice Archer" },
            "rarity": "Common",
            "season": 1,
            "cardNumber": 9,
            "element": "Wind",
            "tribe": "Elf",
            "description": { "th": "เอลฟ์หนุ่มสาวที่กำลังเรียนรู้เส้นทางแห่งธนูและสายลม", "en": "A young elf learning the way of the bow and the wind." },
            "story": { "th": "สำหรับชาวเอลฟ์ การยิงธนูเป็นมากกว่าการต่อสู้ มันคือศิลปะและการทำสมาธิ นักธนูฝึกหัดใช้เวลาหลายปีในการเรียนรู้ที่จะ 'ฟัง' เสียงของสายลมและปล่อยลูกธนูให้เป็นหนึ่งเดียวกับมัน แม้ฝีมือจะยังไม่เทียบเท่าปรมาจารย์ แต่สายตาที่เฉียบคมและความนิ่งของพวกเขาคือภัยคุกคามที่น่ากลัวในสนามรบ", "en": "For the elves, archery is more than combat; it is an art and a meditation. Apprentice archers spend years learning to 'listen' to the wind and let their arrows become one with it. Though their skills do not yet match the masters, their sharp eyes and steady hands are a formidable threat on the battlefield." },
            "stats": { "attack": 16, "defense": 8, "speed": 18, "hp": 29 },
            "frontImage": placeholderFront,
            "backImage": newCardBackUrl
        },
        {
            "id": "1-Common-10",
            "name": { "th": "กิ้งก่าหนองน้ำ", "en": "Swamp Lizard" },
            "rarity": "Common",
            "season": 1,
            "cardNumber": 10,
            "element": "Water",
            "tribe": "Beast",
            "description": { "th": "นักล่าซุ่มโจมตีที่พรางตัวอย่างไร้ที่ติในหนองน้ำที่ขุ่นมัว", "en": "An ambush predator that camouflages perfectly in murky swamps." },
            "story": { "th": "กิ้งก่าหนองน้ำสามารถอยู่นิ่งใต้น้ำได้นานหลายชั่วโมง โดยโผล่มาเพียงดวงตาเพื่อรอคอยเหยื่อที่ไม่ระวังตัว เมื่อโอกาสมาถึง มันจะพุ่งตัวออกจากน้ำด้วยความเร็วสูงและงับเหยื่อด้วยขากรรไกรที่แข็งแรง ผิวหนังที่เป็นเมือกของมันมีพิษอ่อนๆ ที่ทำให้เหยื่อเคลื่อนไหวช้าลง", "en": "The Swamp Lizard can remain motionless underwater for hours, with only its eyes breaking the surface, waiting for unsuspecting prey. When the opportunity arises, it lurches from the water with surprising speed, snapping its powerful jaws. Its slimy skin carries a mild toxin that slows its victims." },
            "stats": { "attack": 17, "defense": 11, "speed": 12, "hp": 31 },
            "frontImage": placeholderFront,
            "backImage": newCardBackUrl
        },
        {
            "id": "1-Common-11",
            "name": { "th": "โกเลมดินเหนียว", "en": "Clay Golem" },
            "rarity": "Common",
            "season": 1,
            "cardNumber": 11,
            "element": "Earth",
            "tribe": "Machine",
            "description": { "th": "รูปปั้นดินเหนียวที่ถูกทำให้มีชีวิตด้วยเวทมนตร์พื้นฐาน", "en": "A clay statue brought to life by basic magic." },
            "story": { "th": "โกเลมดินเหนียวเป็นผู้รับใช้ที่ถูกสร้างขึ้นโดยนักเวทย์ระดับล่างเพื่อทำงานหนักต่างๆ เช่น การก่อสร้างหรือการป้องกัน มันไม่มีความคิดเป็นของตัวเองและจะทำตามคำสั่งง่ายๆ ที่ได้รับมาเท่านั้น ร่างกายของมันสามารถคืนรูปได้หากได้รับความเสียหาย แต่จะอ่อนแออย่างยิ่งต่อน้ำปริมาณมากซึ่งจะทำให้มันละลายกลับเป็นโคลน", "en": "Clay Golems are constructs created by low-level mages for manual labor, such as construction or basic defense. It has no will of its own and only follows simple commands. Its body can regenerate from damage, but it is extremely vulnerable to large amounts of water, which will dissolve it back into mud." },
            "stats": { "attack": 11, "defense": 18, "speed": 6, "hp": 40 },
            "frontImage": placeholderFront,
            "backImage": newCardBackUrl
        },
        {
            "id": "1-Common-12",
            "name": { "th": "ซอมบี้เดินดิน", "en": "Shambling Zombie" },
            "rarity": "Common",
            "season": 1,
            "cardNumber": 12,
            "element": "Dark",
            "tribe": "Undead",
            "description": { "th": "ศพเดินได้ที่เคลื่อนไหวด้วยความหิวโหยในสิ่งมีชีวิต", "en": "A walking corpse driven by a hunger for the living." },
            "story": { "th": "ซอมบี้คือผลลัพธ์อันน่าสยดสยองของคำสาปหรือโรคระบาดร้ายแรง พวกมันเคลื่อนไหวอย่างเชื่องช้าแต่ไม่รู้จักเหน็ดเหนื่อย สิ่งเดียวที่ขับเคลื่อนพวกมันคือความปรารถนาที่จะกินเนื้อสด แม้จะกำจัดได้ไม่ยากเมื่ออยู่ตัวเดียว แต่ฝูงซอมบี้จำนวนมากสามารถล้มอาณาจักรที่แข็งแกร่งที่สุดได้", "en": "Zombies are the horrifying result of a vile curse or plague. They move slowly but tirelessly, driven only by their instinctual desire to consume living flesh. While easy to dispatch individually, a massive horde of them can overwhelm the strongest of kingdoms." },
            "stats": { "attack": 13, "defense": 13, "speed": 4, "hp": 38 },
            "frontImage": placeholderFront,
            "backImage": newCardBackUrl
        },
        {
            "id": "1-Common-13",
            "name": { "th": "พิกซี่จอมซน", "en": "Mischievous Pixie" },
            "rarity": "Common",
            "season": 1,
            "cardNumber": 13,
            "element": "Light",
            "tribe": "Fairy",
            "description": { "th": "ภูตตัวน้อยที่ชอบเล่นตลกกับนักเดินทางผู้โชคร้าย", "en": "A tiny fae that loves to play pranks on unlucky travelers." },
            "story": { "th": "พิกซี่เป็นสิ่งมีชีวิตที่เต็มไปด้วยความอยากรู้อยากเห็น พวกมันชอบซ่อนของ นำทางนักเดินทางให้หลงป่า หรือผูกเชือกรองเท้าของคนที่กำลังหลับ การกระทำของพวกมันส่วนใหญ่ไม่มีพิษมีภัย แต่บางครั้งการเล่นตลกของพวกมันก็อาจนำไปสู่สถานการณ์อันตรายได้โดยไม่ได้ตั้งใจ ว่ากันว่าเสียงหัวเราะของพิกซี่สามารถรักษาบาดแผลเล็กๆ น้อยๆ ได้", "en": "Pixies are creatures of immense curiosity. They enjoy hiding things, leading travelers astray in the woods, or tying the shoelaces of sleeping people together. Most of their actions are harmless, but sometimes their pranks can unintentionally lead to dangerous situations. It is said the sound of a pixie's laugh can heal minor wounds." },
            "stats": { "attack": 7, "defense": 9, "speed": 23, "hp": 22 },
            "frontImage": placeholderFront,
            "backImage": newCardBackUrl
        },
        {
            "id": "1-Common-14",
            "name": { "th": "ออร์คทหารเลว", "en": "Orc Grunt" },
            "rarity": "Common",
            "season": 1,
            "cardNumber": 14,
            "element": "Earth",
            "tribe": "Orc",
            "description": { "th": "นักรบออร์คระดับล่างที่ใช้พละกำลังเข้าตัดสินปัญหาทุกอย่าง", "en": "A low-ranking orc warrior who solves everything with brute force." },
            "story": { "th": "ออร์คทหารเลวคือทหารราบในกองทัพออร์ค พวกมันถูกฝึกให้เชื่อฟังคำสั่งและพุ่งเข้าใส่ศัตรูโดยไม่ลังเล แม้จะไม่ฉลาดนัก แต่พละกำลังตามธรรมชาติและความดุร้ายของพวกมันก็เป็นสิ่งที่น่าเกรงขาม พวกมันเคารพในความแข็งแกร่งเหนือสิ่งอื่นใด และมักจะต่อสู้กันเองเพื่อจัดลำดับชั้นในฝูง", "en": "The Orc Grunt is the infantry of the orc hordes. They are trained to obey orders and charge at the enemy without hesitation. While not particularly intelligent, their natural strength and ferocity are formidable. They respect strength above all else and often fight amongst themselves to establish a pecking order." },
            "stats": { "attack": 20, "defense": 14, "speed": 8, "hp": 36 },
            "frontImage": placeholderFront,
            "backImage": newCardBackUrl
        },
        {
            "id": "1-Common-15",
            "name": { "th": "ลูกกริฟฟิน", "en": "Griffin Hatchling" },
            "rarity": "Common",
            "season": 1,
            "cardNumber": 15,
            "element": "Wind",
            "tribe": "Beast",
            "description": { "th": "ลูกของสัตว์ในตำนาน แม้จะยังบินไม่ได้แต่กรงเล็บก็แหลมคม", "en": "The young of a legendary beast. Though it cannot fly yet, its claws are sharp." },
            "story": { "th": "ลูกกริฟฟินเกิดบนรังที่สร้างขึ้นบนยอดเขาที่สูงที่สุด ขนของมันยังคงอ่อนนุ่มและปีกยังไม่แข็งแรงพอที่จะบินได้ แต่สัญชาตญาณนักล่าของมันนั้นเฉียบคมตั้งแต่เกิด มันจะฝึกฝนการต่อสู้โดยการเล่นกับพี่น้องของมัน และเรียนรู้ที่จะคำรามให้ก้องกังวานเหมือนพ่อแม่ของมัน", "en": "Griffin Hatchlings are born in nests built on the highest mountain peaks. Their feathers are still soft and their wings not yet strong enough for flight, but their predatory instincts are sharp from birth. They practice combat by playing with their siblings and learn to roar as majestically as their parents." },
            "stats": { "attack": 16, "defense": 10, "speed": 19, "hp": 27 },
            "frontImage": placeholderFront,
            "backImage": newCardBackUrl
        },
        {
            "id": "1-Common-16",
            "name": { "th": "นักล่าสมบัติทะเลทราย", "en": "Desert Scavenger" },
            "rarity": "Common",
            "season": 1,
            "cardNumber": 16,
            "element": "Earth",
            "tribe": "Human",
            "description": { "th": "ผู้เชี่ยวชาญการเอาชีวิตรอดในทะเลทราย ค้นหาของมีค่าจากซากปรักหักพัง", "en": "An expert in desert survival who finds valuables in ancient ruins." },
            "story": { "th": "ชีวิตในทะเลทรายนั้นโหดร้าย นักล่าสมบัติเหล่านี้เรียนรู้ที่จะอ่านผืนทรายเหมือนหนังสือ พวกเขาสามารถหาแหล่งน้ำที่ซ่อนอยู่และหลีกเลี่ยงพายุทรายได้ พวกเขาดำรงชีวิตด้วยการขุดค้นซากอารยธรรมโบราณที่ถูกฝังกลบ ค้นหาวัตถุโบราณหรือเทคโนโลยีที่ถูกลืมเพื่อนำไปขายในเมืองโอเอซิส", "en": "Life in the desert is harsh. These scavengers have learned to read the sands like a book, able to find hidden water sources and avoid sandstorms. They make their living by excavating the ruins of ancient civilizations buried beneath, searching for artifacts or forgotten technology to sell in the oasis cities." },
            "stats": { "attack": 13, "defense": 11, "speed": 14, "hp": 33 },
            "frontImage": placeholderFront,
            "backImage": newCardBackUrl
        },
        {
            "id": "1-Common-17",
            "name": { "th": "วิสป์วารี", "en": "Water Wisp" },
            "rarity": "Common",
            "season": 1,
            "cardNumber": 17,
            "element": "Water",
            "tribe": "Elemental",
            "description": { "th": "ภูตน้ำขนาดเล็กที่ล่องลอยอยู่เหนือแหล่งน้ำบริสุทธิ์", "en": "A small water spirit that floats above pure water sources." },
            "story": { "th": "วิสป์วารีคือตัวบ่งชี้ถึงความบริสุทธิ์ของแหล่งน้ำ พวกมันจะปรากฏตัวเป็นลูกไฟสีฟ้าที่ลอยนวลอยู่เหนือทะเลสาบและแม่น้ำที่ใสสะอาด พวกมันดูดซับพลังเวทย์จากสายน้ำเพื่อดำรงอยู่ และจะช่วยนำทางสิ่งมีชีวิตที่หลงทางไปยังที่ปลอดภัย ว่ากันว่าน้ำตาของวิสป์มีพลังในการชำระล้างคำสาป", "en": "Water Wisps are indicators of a water source's purity. They appear as gentle blue flames hovering over clear lakes and rivers. They absorb magical energy from the water to sustain themselves and will guide lost creatures to safety. It is said that the tears of a wisp have the power to cleanse curses." },
            "stats": { "attack": 9, "defense": 14, "speed": 15, "hp": 29 },
            "frontImage": placeholderFront,
            "backImage": newCardBackUrl
        },
        {
            "id": "1-Common-18",
            "name": { "th": "ด้วงอัสนี", "en": "Thunder Beetle" },
            "rarity": "Common",
            "season": 1,
            "cardNumber": 18,
            "element": "Thunder",
            "tribe": "Beast",
            "description": { "th": "แมลงที่มีกระดองแข็งและสามารถปล่อยกระแสไฟฟ้าอ่อนๆ ได้", "en": "An insect with a hard shell that can discharge a weak electric current." },
            "story": { "th": "ด้วงอัสนีจะเก็บประจุไฟฟ้าสถิตจากอากาศในวันที่อากาศแห้งไว้ในปีกของมัน เมื่อรู้สึกว่าถูกคุกคาม มันจะถูปีกเข้าด้วยกันเพื่อปล่อยกระแสไฟฟ้าออกมาทำให้ศัตรูเป็นอัมพาตชั่วขณะ แม้ไฟฟ้าของมันจะไม่รุนแรงพอที่จะเป็นอันตรายถึงชีวิต แต่ก็เพียงพอที่จะทำให้มันมีเวลาหนีไปได้", "en": "The Thunder Beetle gathers static electricity from the air on dry days, storing it in its carapace. When threatened, it rubs its wing covers together to release a jolt of electricity, paralyzing its foe for a moment. While its shock is not strong enough to be lethal, it is enough to give it time to escape." },
            "stats": { "attack": 11, "defense": 16, "speed": 13, "hp": 34 },
            "frontImage": placeholderFront,
            "backImage": newCardBackUrl
        },
        {
            "id": "1-Common-19",
            "name": { "th": "แมงมุมยักษ์แห่งพงไพร", "en": "Giant Forest Spider" },
            "rarity": "Common",
            "season": 1,
            "cardNumber": 19,
            "element": "Dark",
            "tribe": "Beast",
            "description": { "th": "นักล่าแปดขาที่ชักใยอันเหนียวหนืดเพื่อดักจับเหยื่อ", "en": "An eight-legged predator that spins sticky webs to trap its prey." },
            "story": { "th": "ในส่วนลึกของป่าทึบ แสงแดดส่องลงมาไม่ถึง ที่นั่นคืออาณาจักรของแมงมุมยักษ์แห่งพงไพร ใยของมันแข็งแรงพอที่จะดักจับนกที่บินผ่าน และพิษของมันสามารถทำให้หมูป่าเป็นอัมพาตได้ในไม่กี่วินาที พวกมันอดทนรอคอยอย่างเงียบเชียบบนใยของมัน สัมผัสแรงสั่นสะเทือนเพียงเล็กน้อยเพื่อรับรู้ถึงเหยื่อที่โชคร้าย", "en": "In the deep, sunless parts of the forest lies the domain of the Giant Forest Spider. Its webs are strong enough to trap birds in flight, and its venom can paralyze a wild boar in seconds. They wait patiently and silently on their webs, feeling the slightest vibration to detect their unfortunate prey." },
            "stats": { "attack": 16, "defense": 13, "speed": 15, "hp": 30 },
            "frontImage": placeholderFront,
            "backImage": newCardBackUrl
        },
        {
            "id": "1-Common-20",
            "name": { "th": "คนแคระช่างเหมือง", "en": "Dwarven Miner" },
            "rarity": "Common",
            "season": 1,
            "cardNumber": 20,
            "element": "Earth",
            "tribe": "Human",
            "description": { "th": "คนแคระผู้แข็งแกร่ง ใช้เวลาทั้งชีวิตในการขุดหาแร่และอัญมณี", "en": "A sturdy dwarf who spends his life digging for ore and gems." },
            "story": { "th": "สำหรับคนแคระ การทำเหมืองไม่ใช่แค่งาน แต่เป็นวิถีชีวิต พวกเขาเกิดและเติบโตใต้ภูเขา เรียนรู้ภาษาของหินและเสียงกระซิบของสายแร่ พลั่วของพวกเขาไม่ได้เป็นเพียงเครื่องมือ แต่เป็นส่วนหนึ่งของร่างกายที่ใช้เปิดเส้นทางใหม่ๆ ในความมืด แม้จะรักสันติ แต่หากใครมารบกวนเหมืองของพวกเขา พลั่วในมือก็พร้อมจะกลายเป็นอาวุธที่น่ากลัวได้ทันที", "en": "For dwarves, mining is not just a job; it's a way of life. They are born and raised beneath the mountains, learning the language of stone and the whispers of ore veins. Their pickaxes are not mere tools, but extensions of their bodies, used to carve new paths in the darkness. Though peaceful, if their mines are disturbed, the same pickaxe becomes a fearsome weapon." },
            "stats": { "attack": 14, "defense": 19, "speed": 7, "hp": 38 },
            "frontImage": placeholderFront,
            "backImage": newCardBackUrl
        },
        {
            "id": "1-Common-21",
            "name": { "th": "เสียงเรียกของไซเรน", "en": "Siren's Call" },
            "rarity": "Common",
            "season": 1,
            "cardNumber": 21,
            "element": "Water",
            "tribe": "Fairy",
            "description": { "th": "สิ่งมีชีวิตงดงามที่ใช้เสียงเพลงล่อลวงนักเดินเรือสู่หายนะ", "en": "A beautiful creature that uses its song to lure sailors to their doom." },
            "story": { "th": "เสียงเพลงของไซเรนคือพรสวรรค์และคำสาป มันไพเราะจนสามารถหยุดหัวใจของบุรุษผู้แข็งแกร่งที่สุดได้ แต่เบื้องหลังเสียงอันงดงามนั้นคือความปรารถนาที่จะลากทุกชีวิตลงสู่ก้นบึ้งของมหาสมุทร พวกมันจะเกาะอยู่บนโขดหินในวันที่หมอกลงจัด ขับขานบทเพลงแห่งความตายให้กับเรือที่แล่นผ่าน", "en": "A siren's song is both a gift and a curse. It is beautiful enough to stop the heart of the strongest man, but behind that beauty lies a desire to drag all life down to the bottom of the ocean. They perch on rocks on foggy days, singing their fatal melodies to passing ships." },
            "stats": { "attack": 10, "defense": 11, "speed": 17, "hp": 29 },
            "frontImage": placeholderFront,
            "backImage": newCardBackUrl
        },
        {
            "id": "1-Common-22",
            "name": { "th": "เกราะเดินได้", "en": "Living Armor" },
            "rarity": "Common",
            "season": 1,
            "cardNumber": 22,
            "element": "Dark",
            "tribe": "Machine",
            "description": { "th": "ชุดเกราะที่ถูกวิญญาณอาฆาตเข้าสิง เคลื่อนไหวได้ด้วยตัวเอง", "en": "A suit of armor possessed by a vengeful spirit, moving on its own." },
            "story": { "th": "ชุดเกราะนี้เคยเป็นของอัศวินผู้ยิ่งใหญ่ที่ถูกหักหลังในสนามรบ วิญญาณของเขาไม่ยอมไปสู่สุคติและยังคงสิงสถิตอยู่ในชุดเกราะเก่าๆ ของตน มันจะเดินวนเวียนอยู่ในปราสาทร้าง คอยโจมตีผู้บุกรุกทุกคนด้วยดาบที่มองไม่เห็นซึ่งกวัดแกว่งด้วยความแค้น เสียงโลหะกระทบกันในความเงียบคือเสียงสุดท้ายที่หลายคนได้ยิน", "en": "This armor once belonged to a great knight betrayed on the battlefield. His spirit refused to pass on, clinging to its old shell. It now wanders the halls of abandoned castles, attacking any intruder with an unseen sword swung by pure vengeance. The clang of metal in the silence is the last sound many hear." },
            "stats": { "attack": 18, "defense": 22, "speed": 5, "hp": 35 },
            "frontImage": placeholderFront,
            "backImage": newCardBackUrl
        },
        {
            "id": "1-Common-23",
            "name": { "th": "ชนเผ่าเร่ร่อนแห่งทุ่งหญ้า", "en": "Plains Nomad" },
            "rarity": "Common",
            "season": 1,
            "cardNumber": 23,
            "element": "Wind",
            "tribe": "Human",
            "description": { "th": "นักรบผู้เติบโตมาบนหลังม้า เชี่ยวชาญการใช้หอกและธนู", "en": "A warrior raised on horseback, skilled with spears and bows." },
            "story": { "th": "สำหรับชนเผ่าเร่ร่อน ทุ่งหญ้าคือบ้านและท้องฟ้าคือหลังคา พวกเขาเดินทางไปตามฤดูกาลและตามฝูงสัตว์ที่พวกเขาเลี้ยง ความผูกพันระหว่างพวกเขากับม้าคู่ใจนั้นลึกซึ้งยิ่งกว่าพี่น้อง พวกเขาสามารถยิงธนูได้อย่างแม่นยำขณะควบม้าด้วยความเร็วสูงสุด ทำให้พวกเขาเป็นกองทหารม้าที่น่าเกรงขามที่สุดในแผ่นดิน", "en": "For the nomads, the plains are their home and the sky their roof. They travel with the seasons, following the herds they raise. The bond between a nomad and their horse is deeper than brotherhood. They can fire arrows with pinpoint accuracy while galloping at full speed, making them the most feared cavalry on the continent." },
            "stats": { "attack": 17, "defense": 10, "speed": 21, "hp": 30 },
            "frontImage": placeholderFront,
            "backImage": newCardBackUrl
        },
        {
            "id": "1-Common-24",
            "name": { "th": "เชื้อรามีชีวิต", "en": "Living Fungus" },
            "rarity": "Common",
            "season": 1,
            "cardNumber": 24,
            "element": "Earth",
            "tribe": "Elemental",
            "description": { "th": "กลุ่มก้อนของเชื้อราที่ได้รับสติปัญญาจากพลังเวทย์ในถ้ำลึก", "en": "A fungal colony that gained sentience from deep cave magic." },
            "story": { "th": "ในถ้ำที่ไม่มีแสงส่องถึงและอุดมไปด้วยพลังเวทย์ เชื้อราได้วิวัฒนาการไปไกลกว่าแค่การย่อยสลายซากศพ พวกมันรวมตัวกันเป็นร่างเดียวและพัฒนาสติปัญญาร่วมกัน มันสามารถปล่อยสปอร์พิษเพื่อป้องกันตัวและสื่อสารกันผ่านเครือข่ายไมซีเลียมใต้ดินที่กว้างใหญ่ไพศาล", "en": "In sunless caves rich with magical energy, fungus has evolved beyond mere decomposition. They have formed a collective consciousness, a single entity made of many. It can release toxic spores to defend itself and communicates through a vast, underground mycelial network." },
            "stats": { "attack": 12, "defense": 16, "speed": 7, "hp": 39 },
            "frontImage": placeholderFront,
            "backImage": newCardBackUrl
        },
        {
            "id": "1-Common-25",
            "name": { "th": "ซาลาแมนเดอร์อัสนี", "en": "Volt Salamander" },
            "rarity": "Common",
            "season": 1,
            "cardNumber": 25,
            "element": "Thunder",
            "tribe": "Beast",
            "description": { "th": "สัตว์ครึ่งบกครึ่งน้ำที่ผิวหนังสามารถสร้างและเก็บประจุไฟฟ้าได้", "en": "An amphibian whose skin can generate and store electricity." },
            "story": { "th": "ซาลาแมนเดอร์อัสนีอาศัยอยู่ในบริเวณที่เกิดพายุฝนฟ้าคะนองบ่อยครั้ง พวกมันจะปีนขึ้นไปบนที่สูงเพื่อรอรับสายฟ้าฟาดเพื่อชาร์จพลังงาน ผิวหนังที่เป็นเมือกของมันทำหน้าที่เป็นตัวเก็บประจุธรรมชาติ เมื่อถูกคุกคาม มันจะปล่อยพลังงานทั้งหมดออกมาในครั้งเดียวเพื่อช็อตศัตรูที่อยู่รอบตัว", "en": "Volt Salamanders thrive in regions with frequent thunderstorms. They climb to high places to absorb lightning strikes, charging their bodies. Their slimy skin acts as a natural capacitor. When threatened, they can discharge all their stored energy at once, shocking everything around them." },
            "stats": { "attack": 18, "defense": 13, "speed": 16, "hp": 28 },
            "frontImage": placeholderFront,
            "backImage": newCardBackUrl
        },
        {
            "id": "1-Common-26",
            "name": { "th": "นักบวชฝึกหัด", "en": "Acolyte Priest" },
            "rarity": "Common",
            "season": 1,
            "cardNumber": 26,
            "element": "Light",
            "tribe": "Human",
            "description": { "th": "ผู้รับใช้แห่งแสงที่อุทิศตนเพื่อเรียนรู้มนต์แห่งการรักษา", "en": "A servant of the light, dedicated to learning healing arts." },
            "story": { "th": "นักบวชฝึกหัดใช้เวลาส่วนใหญ่ในการสวดมนต์และศึกษาคัมภีร์ศักดิ์สิทธิ์ พวกเขาเรียนรู้ที่จะเชื่อมโยงกับพลังแห่งแสงสว่างเพื่อบรรเทาความเจ็บปวดและรักษาบาดแผล แม้พลังของพวกเขาจะยังไม่แข็งแกร่งพอที่จะรักษาอาการบาดเจ็บสาหัสได้ แต่ในยามสงคราม แสงสว่างเล็กๆ ของพวกเขาก็คือความหวังในสนามรบที่มืดมิด", "en": "Acolytes spend their days in prayer and study of holy texts. They learn to channel the power of light to soothe pain and mend wounds. Though their power is not yet strong enough to heal grave injuries, in times of war, their small light is a beacon of hope on a dark battlefield." },
            "stats": { "attack": 8, "defense": 14, "speed": 11, "hp": 34 },
            "frontImage": placeholderFront,
            "backImage": newCardBackUrl
        },
        {
            "id": "1-Common-27",
            "name": { "th": "โกเลมหิน", "en": "Rock Golem" },
            "rarity": "Common",
            "season": 1,
            "cardNumber": 27,
            "element": "Earth",
            "tribe": "Elemental",
            "description": { "th": "ภูตหินที่เกิดจากการรวมตัวของก้อนหินด้วยพลังเวทย์", "en": "A stone spirit formed by magically bound rocks." },
            "story": { "th": "โกเลมหินไม่มีชีวิตจิตใจ แต่จะปกป้องสถานที่ที่มันถือกำเนิดขึ้นตามสัญชาตญาณ มันจะอยู่นิ่งเหมือนก้อนหินธรรมดาจนกว่าจะมีผู้บุกรุกเข้ามาใกล้ จากนั้นมันจะลุกขึ้นยืนและโจมตีด้วยหมัดหินที่หนักหน่วง ร่างกายของมันแข็งแกร่งอย่างยิ่งและแทบไม่ได้รับความเสียหายจากการโจมตีทางกายภาพธรรมดา", "en": "The Rock Golem has no true consciousness but instinctively protects the place of its birth. It will lie dormant, indistinguishable from other rocks, until an intruder comes near. It then rises and attacks with its heavy stone fists. Its body is extremely durable and takes little damage from conventional physical attacks." },
            "stats": { "attack": 15, "defense": 24, "speed": 4, "hp": 42 },
            "frontImage": placeholderFront,
            "backImage": newCardBackUrl
        },
        {
            "id": "1-Common-28",
            "name": { "th": "อิมพ์", "en": "Imp" },
            "rarity": "Common",
            "season": 1,
            "cardNumber": 28,
            "element": "Fire",
            "tribe": "Abyssal",
            "description": { "th": "ปีศาจตัวเล็กจอมเจ้าเล่ห์ที่ชอบก่อความวุ่นวายด้วยไฟ", "en": "A small, cunning demon that loves to cause trouble with fire." },
            "story": { "th": "อิมพ์เป็นปีศาจระดับต่ำสุดที่ถูกอัญเชิญมายังโลกมนุษย์ พวกมันอ่อนแอแต่ก็ชดเชยด้วยความเจ้าเล่ห์และจำนวนที่มากมาย พวกมันชอบแอบซ่อนอยู่ในที่มืดและปาลูกไฟเล็กๆ ใส่ผู้คนเพื่อความสนุกสนาน แม้จะดูน่ารำคาญมากกว่าอันตราย แต่ฝูงอิมพ์จำนวนมากก็สามารถเผาทำลายหมู่บ้านทั้งหมู่บ้านได้", "en": "Imps are the lowest rank of demons summoned to the mortal plane. They are weak but make up for it with cunning and numbers. They enjoy hiding in dark places and throwing small fireballs at people for fun. While more of an annoyance than a real threat, a swarm of them can burn down an entire village." },
            "stats": { "attack": 17, "defense": 9, "speed": 19, "hp": 25 },
            "frontImage": placeholderFront,
            "backImage": newCardBackUrl
        },
        {
            "id": "1-Common-29",
            "name": { "th": "ลูกงูทะเล", "en": "Sea Serpent Hatchling" },
            "rarity": "Common",
            "season": 1,
            "cardNumber": 29,
            "element": "Water",
            "tribe": "Dragon",
            "description": { "th": "ลูกของพญานาคแห่งท้องทะเล มีขนาดเท่าเรือเล็กแต่ยังขี้เล่น", "en": "The young of a great sea dragon, the size of a small boat but still playful." },
            "story": { "th": "ลูกงูทะเลมีความอยากรู้อยากเห็นเกี่ยวกับโลกผิวน้ำ พวกมันมักจะว่ายตามเรือของชาวประมงและพ่นน้ำ", "en": "" },
            "stats": { "attack": 14, "defense": 15, "speed": 18, "hp": 33 },
            "frontImage": placeholderFront,
            "backImage": newCardBackUrl
        }
    ];
    return allCards;
};
export const fullCardDatabase = generateAllCards();