// FIX: Import `CardRarity` to resolve type error.
import { Card, CardRarity } from '../types';

// This file contains pre-generated card data for Season 1 to ensure a fast initial app load.
// The rest of the card data will be generated by AI in the background.

const placeholderFront = 'https://images.unsplash.com/photo-1534796636912-3b95b3ab5986?q=80&w=1974';
// FIX: Using updated back image consistent with the database migration.
const placeholderBack = "https://i.imgur.com/z11n4j7.jpeg";

export const initialCardData: Card[] = [
  // Example data structure, in a real scenario this would contain all 116 cards for Season 1.
  // Common
  // FIX: Converted name, description, and story to objects and added stats.
  {
    id: "1-Common-1",
    name: { en: "Goblin Scout", th: "ก็อบลินสอดแนม" },
    rarity: "Common",
    season: 1,
    cardNumber: 1,
    element: "Earth",
    tribe: "Orc",
    description: { en: "A swift scout, always looking for trouble.", th: "หน่วยสอดแนมผู้ปราดเปรียว คอยมองหาปัญหาอยู่เสมอ" },
    story: { en: "These nimble creatures form the vanguard of any goblin war party, using their speed to map terrain and identify enemy weaknesses.", th: "สิ่งมีชีวิตที่ว่องไวเหล่านี้เป็นแนวหน้าของกองทัพก็อบลิน ใช้ความเร็วในการสำรวจภูมิประเทศและชี้จุดอ่อนของศัตรู" },
    stats: { attack: 10, defense: 5, speed: 15, hp: 20 },
    frontImage: placeholderFront,
    backImage: placeholderBack,
  },
  {
    id: "1-Common-2",
    name: { en: "Forest Spirit", th: "ภูตป่า" },
    rarity: "Common",
    season: 1,
    cardNumber: 2,
    element: "Wind",
    tribe: "Fairy",
    description: { en: "A shy protector of the woods.", th: "ผู้พิทักษ์แห่งพงไพรที่ขี้อาย" },
    story: { en: "Born from the ancient trees, these spirits nurture the forest and guide lost travelers, but will defend their home with surprising ferocity.", th: "ถือกำเนิดจากต้นไม้โบราณ ภูตเหล่านี้คอยดูแลป่าและนำทางนักเดินทางที่หลงทางให้กลับบ้าน แต่จะปกป้องบ้านของตนด้วยความดุร้ายอย่างน่าประหลาดใจ" },
    stats: { attack: 8, defense: 12, speed: 12, hp: 25 },
    frontImage: placeholderFront,
    backImage: placeholderBack,
  },
  // Rare
  {
    id: "1-Rare-1",
    name: { en: "Knight of the Sun", th: "อัศวินแห่งตะวัน" },
    rarity: "Rare",
    season: 1,
    cardNumber: 1,
    element: "Light",
    tribe: "Human",
    description: { en: "A valiant knight whose armor shines like the sun.", th: "อัศวินผู้กล้าหาญที่ชุดเกราะส่องประกายดุจดวงอาทิตย์" },
    story: { en: "A sworn protector of the kingdom, this knight channels the power of light to smite evil and defend the innocent.", th: "ผู้พิทักษ์แห่งอาณาจักรผู้สาบานตน อัศวินผู้นี้ใช้พลังแห่งแสงเพื่อกำจัดความชั่วร้ายและปกป้องผู้บริสุทธิ์" },
    stats: { attack: 25, defense: 30, speed: 20, hp: 40 },
    frontImage: placeholderFront,
    backImage: placeholderBack,
  },
  // Super Rare
  {
    id: "1-Super Rare-1",
    name: { en: "Abyssal Serpent", th: "นาคาอเวจี" },
    rarity: "Super Rare",
    season: 1,
    cardNumber: 1,
    element: "Dark",
    tribe: "Dragon",
    description: { en: "A terrifying serpent from the darkest depths.", th: "อสรพิษน่าสะพรึงกลัวจากห้วงลึกที่มืดมิดที่สุด" },
    story: { en: "Dwelling in the sunless trenches of the ocean, this ancient serpent emerges only to drag ships and sailors to a watery grave.", th: "อาศัยอยู่ในร่องลึกไร้แสงของมหาสมุทร อสรพิษโบราณนี้จะปรากฏตัวเพื่อลากเรือและลูกเรือลงสู่สุสานใต้ท้องทะเลเท่านั้น" },
    stats: { attack: 40, defense: 35, speed: 30, hp: 50 },
    frontImage: placeholderFront,
    backImage: placeholderBack,
  },
  // ... This would continue for all 116 cards in Season 1
  {
    id: "1-Legendary Rare-1",
    name: { en: "Genesis Dragon, Alpha", th: "มังกรปฐมกาล, อัลฟ่า" },
    rarity: "Legendary Rare",
    season: 1,
    cardNumber: 1,
    element: "Divine",
    tribe: "Dragon",
    description: { en: "The first dragon, from whom all others descend.", th: "มังกรตัวแรกสุด บรรพบุรุษของมังกรทั้งปวง" },
    story: { en: "A mythical being of immense power, said to have shaped the world with its fiery breath at the dawn of time. Its scales shimmer with cosmic energy.", th: "สิ่งมีชีวิตในตำนานผู้มีพลังมหาศาล กล่าวกันว่าเป็นผู้สร้างโลกด้วยลมหายใจแห่งเพลิงในรุ่งอรุณแห่งกาลเวลา เกล็ดของมันส่องประกายด้วยพลังแห่งจักรวาล" },
    stats: { attack: 95, defense: 90, speed: 80, hp: 100 },
    frontImage: placeholderFront,
    backImage: placeholderBack,
  },
];

// Fill the rest of Season 1 with placeholder cards to ensure correct counts
const rarities: { rarity: CardRarity, count: number }[] = [
    { rarity: 'Common', count: 50 },
    { rarity: 'Rare', count: 30 },
    { rarity: 'Super Rare', count: 15 },
    { rarity: 'Ultra Rare', count: 10 },
    { rarity: 'Ultimate Rare', count: 5 },
    { rarity: 'Secret Rare', count: 3 },
    { rarity: 'Parallel Rare', count: 2 },
    { rarity: 'Legendary Rare', count: 1 },
];

rarities.forEach(({ rarity, count }) => {
    const existingCount = initialCardData.filter(c => c.rarity === rarity).length;
    for (let i = existingCount + 1; i <= count; i++) {
        // FIX: Corrected placeholder card structure to match the Card interface.
        initialCardData.push({
            id: `1-${rarity}-${i}`,
            name: { en: `[Placeholder] ${rarity} Card`, th: `[ข้อมูลชั่วคราว]` },
            rarity: rarity,
            season: 1,
            cardNumber: i,
            element: 'Fire',
            tribe: 'Human',
            description: { en: '', th: '' },
            story: { en: '', th: '' },
            stats: { attack: 5, defense: 5, speed: 5, hp: 10 },
            frontImage: placeholderFront,
            backImage: placeholderBack,
        });
    }
});